# https://hub.docker.com/r/pytorch/pytorch/tags

# dvel mode has nvcc while runtime has not
FROM pytorch/pytorch:1.12.1-cuda11.3-cudnn8-devel

# install ssome basic tools
RUN apt-get update && apt-get install -y --no-install-recommends \
        --allow-change-held-packages \
        build-essential \
        autotools-dev \
        rsync \
        curl \
        cmake \
        wget \
        vim \
        tmux \
        htop \
        git \
        unzip \
        libnccl2 \
        libnccl-dev \
        ca-certificates \
        libjpeg-dev \
        htop \ 
        sudo \
        g++ \
        gcc \
        apt-utils \
        libosmesa6-dev \
        net-tools


